version: v1
server:
  port: 8082
  servlet:
    context-path: /@project.artifactId@
datasource:
  pgs:
    jdbcUrl: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USER}

