version: v1
server:
  port: 8082
  servlet:
    context-path: /@project.artifactId@
datasource:
  pgs:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    password: 123456
    username: postgres

